const illustrationStyles = [
  "realism",
  "abstract",
  "surrealism",
  "pop-art",
  "cubism",
  "expressionism",
  "minimalism",
  "impressionism",
  "contemporary",
  "modern",
  "postmodern",
  "vector",
  "digital",
  "traditional",
  "flat-art",
  "3d-illustration",
  "psychedelic",
  "graffiti",
  "sketch",
  "cartoon",
  "anime",
  "manga",
  "comic",
  "watercolor",
  "oil-painting",
  "acrylic-painting",
  "pastel",
  "charcoal",
  "pencil",
  "ink",
  "digital-painting",
  "mixed-media",
  "collage",
];

export default illustrationStyles;
